databases:
  - name: abc_cod
    databaseName: abc_cod
    user: abc_cod

services:
  - type: web
    name: abc_cod
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: abc_cod
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
